In [2]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5,6,7,8]

In [3]:
x1 = np.array(l1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(l1, dtype="float32")
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,12,dtype="float")

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [12]:
np.arange(4,5,0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
np.linspace(1.,7.,12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
x.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [24]:
x = np.array(([1,2,3,4],[5,6,7,8]))
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
np.resize(x,(5,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

# Ejercicios

1. Crear un array de datos con valores entre 5 y 120
2. Crear una matriz 4x4 con los valores de 0 hasta 15
3. Crear la identidad 7x7
4. Crear un array de 20 elementos y transformarlos en una matrix 5x4
5. Crear un array con 20 numeros con los valores entre 0 y 5 espaciados de forma uniforme

In [6]:
np.arange(5,120)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [18]:
x = np.arange(16)
x = x.reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
x = np.arange(20)
x = x.reshape((5,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
x = np.linspace(0,5,20)
x

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de los arrays

In [33]:
x = np.arange(12)
x = x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
dim = x.ndim
print(f'El numero de dimensiones es {dim}')

El numero de dimensiones es 2


In [40]:
forma = x.shape
print(f'La matriz es tiene {forma[0]} filas y {forma[1]} columnas')

La matriz es tiene 3 filas y 4 columnas


In [41]:
x.dtype

dtype('int32')

In [43]:
tamaño_bytes = x.itemsize
print(f'Cada numero dentro de la matriz ocupa {tamaño_bytes} bytes de informacion.')

Cada numero dentro de la matriz ocupa 4 bytes de informacion.


In [44]:
memory_allocated = x.data 
print(f'El espacio de memoria donde esta alojado el array es {memory_allocated}')

El espacio de memoria donde esta alojado el array es <memory at 0x000002132B63A120>


In [45]:
x[2]

array([ 8,  9, 10, 11])

In [46]:
x[2,1]

9

In [47]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
x[1:3,0:2 ]

array([[3, 4],
       [6, 7]])

In [51]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
y[3:8]

array([3, 4, 5, 6, 7])

In [55]:
y[1:7:2]

array([1, 3, 5])

In [56]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [58]:
y[z]

array([10,  9,  8,  7])

In [60]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [62]:
cond = (x < 25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [64]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [68]:
x.dtype

dtype('int32')

In [71]:
print(f'Como el arreglo es de tipo int32 convierte el dato float a int.')
x[5] = 3.1415
x

Como el arreglo es de tipo int32 convierte el dato float a int.


array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Copias y vistas de arrays

In [85]:
x = np.arange(10)

In [86]:
print(f'Aca no creamos un nuevo array, solo estamos referenciando con una nueva variable al array anteiormente creado y=x')
y = x

Aca no creamos un nuevo array, solo estamos referenciando con una nueva variable al array anteiormente creado y=x


In [87]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
print(f'Si hacemos una copia del array, estos seran diferentes z != x')
z = x.copy()
z

Si hacemos una copia del array, estos seran diferentes z != x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
z is x

False

In [91]:
y is x

True

In [94]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [97]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
print(f'Si modificamos t, solo ha cambiado la vista mas no x')

Si modificamos t, solo ha cambiado la vista mas no x


In [101]:
s = x[0:2,1:3]
s
print(f'Seleccionar una parte de un array, es una vista')
s

Seleccionar una parte de un array, es una vista


array([[1, 2],
       [6, 7]])

# Funciones Universales (ufunc)
- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum

In [102]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [105]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [106]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [107]:
alpha = np.linspace(0,2*np.pi,4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [108]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [109]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [110]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [111]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [112]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [113]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [114]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [116]:
np.log(x[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [117]:
np.log2(x[1:])

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [119]:
np.log10(x[1:])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [121]:
np.sum(x)

45

In [123]:
np.nansum(x)

45

In [125]:
np.prod(x)

0

In [126]:
np.mean(x)

4.5

In [127]:
np.median(x)

4.5

In [128]:
np.min(x)

0

In [129]:
np.max(x)

9

In [130]:
np.std(x)

2.8722813232690143

In [131]:
np.var(x)

8.25

In [136]:
min_pos = np.argmin(x)
print(f'La posicion donde se encuentra el valor mas pequeño es: {min_pos}')

La posicion donde se encuentra el valor mas pequeño es: 0


In [137]:
max_pos = np.argmax(x)
print(f'La posicion donde se encuentra el valor mas pequeño es: {max_pos}')

La posicion donde se encuentra el valor mas pequeño es: 9


In [143]:
np.percentile(x,q=0.95)

0.08549999999999999

In [146]:
y = np.array([True, False, False, True])

In [149]:
any = np.any(y)
print(f'Existe algun valor verdadero en el arreglo? {any}')

Existe algun valor verdadero en el arreglo True


In [150]:
all = np.all(y)
print(f'Todos los valores son verdadero en el arreglo? {all}')

Todos los valores son verdadero en el arreglo? False


In [152]:
print(f'Generamos un arreglo de 3 filas y 5 columnas con valores entre 0 y 1')
z = np.random.random((3,5))
z

Generamos un arreglo de 3 filas y 5 columnas con valores entre 0 y 1


array([[0.98283991, 0.44814644, 0.38987333, 0.17680379, 0.60212674],
       [0.50911664, 0.82958372, 0.42873053, 0.65471385, 0.58254767],
       [0.72760132, 0.60574178, 0.33146052, 0.72758817, 0.63588603]])

In [153]:
z.sum()

8.632760454036301

In [158]:
print('Suma por columnas')
z.sum(axis = 0)

Suma por columnas


array([2.21955788, 1.88347194, 1.15006438, 1.55910581, 1.82056044])

In [159]:
print('Suma por filas')
z.sum(axis=1)

Suma por filas


array([2.59979021, 3.00469242, 3.02827782])

In [161]:
np.random.seed(2019)
np.random.random((3,5))

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])