In [7]:
import numpy as np
import pandas as pd

# ¿ Que es el muestreo ?

En todo estudio estadistico se distingue entre pobalcion (conjunto de sujetos con una o mas caracteristicas que deseamos estudiar o medir) y muestra (subconjunto de la poblacion).

* Exploratorio o Descriptio: Estadistica Descriptiva
* Inferencial o Confirmatorio: Estadistica Inferencial

**Pasos en un estudio inferencial:**
- Establecer la caracteristica que se desea estimar o la hipotesis que se desea contrastar.
<br><br>
- Determinar la informacion (datos) que se necesitan.
<br><br>
- Diseñar un experimento que permita recoger los datos:
<br><br>
    - Definir el tipo y tamaño de la muestra
    - Definir las tecnicas correctas para realizar las inferencias deseadas a partir de la muestra
<br><br>
- Tomar una muestra y medir los datos deseados sobre los individuos que la forman.
<br><br>
- Obtener conclusiones. 
<br><br>
- Si las conclusiones son fiables y suficientes, redactar un informe

# Muestreo Aleatorio con Reposicion

Consiste en obtener una muestra de una poblacion de tal modo que todas las muestras del mismo tamaño sean equiprobables (igual de probables).

## Ejemplo:
Consideremos una urna de 100 bolas numeradas del 1 al 100, la cual será la población de nuestro experimento.

In [4]:
print('Urna con bolas enumeradas del 1 al 100.')
np.arange(1,101,1)

Urna con bolas enumeradas del 1 al 100.


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Para simular el muestreo **con reposicion** (es decir, devolveremos a la urna la bola que extraigamos)en Python haremos lo siguiente:

In [6]:
bolas = np.random.choice(101, 15, replace=True)
bolas

array([18, 61, 33,  5, 34, 37, 81, 42, 47, 40, 67, 62, 92, 68, 13])

Realicemos un ejemplo con el dataset de flores, considerando que hay reposicion.

In [14]:
iris = pd.read_csv(r"..\datasets\iris.csv", sep=",")
iris.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [28]:
iris.sample(n = 10, replace= True)

sepal_length  sepal_width  petal_length  petal_width     species
112           6.8          3.0           5.5          2.1   virginica
27            5.2          3.5           1.5          0.2      setosa
147           6.5          3.0           5.2          2.0   virginica
41            4.5          2.3           1.3          0.3      setosa
76            6.8          2.8           4.8          1.4  versicolor
147           6.5          3.0           5.2          2.0   virginica
58            6.6          2.9           4.6          1.3  versicolor
4             5.0          3.6           1.4          0.2      setosa
148           6.2          3.4           5.4          2.3   virginica
1             4.9          3.0           1.4          0.2      setosa

Como podemos observar hemos obtenido 10 muestras aleatorias y al ser con reposicion hemos obtenido 2 veces la flor 25.

# Muestreo Aleatorio sin Reposicion

Consiste en obtener una muestra de una poblacion, en el ejemplo de la urna con 100 bolas tendriamos repetir 15 veces 
el proceso de sacar una bola pero ahora sin devolverla. Esto seria llamado una muestra aleatoria sin reposicion.

In [30]:
print('Urna con bolas enumeradas del 1 al 100.')
np.arange(1,101,1)

Urna con bolas enumeradas del 1 al 100.


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Retiramos 15 bolas sin reposicion.

In [32]:
bolas = np.random.choice(101, 15, replace=False)
bolas

array([35, 39, 18, 30, 66, 41, 50, 15, 64,  0, 14, 63, 65, 76,  8])

Para nuestro dataset de iris podemos realizar el mismo procedimiento.

In [35]:
iris.sample(n = 10, replace= False)

sepal_length  sepal_width  petal_length  petal_width     species
68            6.2          2.2           4.5          1.5  versicolor
31            5.4          3.4           1.5          0.4      setosa
117           7.7          3.8           6.7          2.2   virginica
107           7.3          2.9           6.3          1.8   virginica
28            5.2          3.4           1.4          0.2      setosa
17            5.1          3.5           1.4          0.3      setosa
24            4.8          3.4           1.9          0.2      setosa
63            6.1          2.9           4.7          1.4  versicolor
116           6.5          3.0           5.5          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica

# ¿ Es equivalente realizar un muestreo con reposicion vs sin reposicion?

Si el tamaño de la poblacion es muy grande en relacion al de la muestra (por dar una regla, digamos que, al menos, unas 1000 veces mayor). En la practica casi siempre se utiliza el muestro **sin reposicion**, porque no tiene sentido entrevistar al mismo sujeto dos veces. 